name: AccessEnvVar

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - abc
        - xyz
      message:
        required: true
        description: Custom message
      environment:
        description: Target environment (e.g. dev, staging)
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}   # Use input here

    steps:
    - name: Send greeting
      run: |
        echo "${{ github.event.inputs.message }} ${{ github.event.inputs.name }}"
        echo "ENV VAR: ${{ vars.DEV_ENV }}"
