name: Use Environment-Specific Variables

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select environment'
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Production

jobs:
  show-env-vars:
    runs-on: ubuntu-latest

    # This links the job to the selected environment so it can access its variables
    environment:
      name: ${{ github.event.inputs.target_env }}

    steps:
      - name: Echo environment and variables
        run: |
          echo "Selected environment: ${{ github.event.inputs.target_env }}"
          echo "DEV_ENV = $DEV_ENV"
          echo "PROD_ENV = $PROD_ENV"
        env:
          DEV_ENV: ${{ vars.DEV_ENV }}
          PROD_ENV: ${{ vars.PROD_ENV }}
