name: Access Environment-Specific Variables

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Choose environment to deploy'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - production

jobs:
  print-env:
    runs-on: ubuntu-latest

    # This ensures GitHub loads the right environment's variables/secrets
    environment:
      name: ${{ github.event.inputs.target_env }}

    steps:
      - name: Echo selected environment
        run: echo "Running in ${{ github.event.inputs.target_env }} environment"

      - name: Read and print environment-specific variables
        run: |
          echo "ENV_VAR = $ENV_VAR"
          echo "OTHER_VAR = $OTHER_VAR"
        env:
          ENV_VAR: ${{ vars.ENV_VAR }}
          OTHER_VAR: ${{ vars.OTHER_VAR }}
