name: Test Vars

on: [push]

jobs:
  test-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print a GitHub variable
        run: echo "My variable is ${{ vars.MY_VAR }}"
        run: echo "My variable is - ${{ vars.DEV_ENV }}"
