name: Test Vars
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - development
          - Production
jobs:
  test-vars:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Print a GitHub variable
        run: |
          echo "My variable is ${{ vars.MY_VAR }}"
          echo "My development env is ${{ vars.DEV_ENV }}"
          echo "My Prod var is ${{ vars.MY_VAR }}"
          echo "My Dev var is ${{ vars.MY_VAR }}"

      - name: Print updated GitHub variable
        run: |
          echo "DEV_ENV=xyz" >> $GITHUB_ENV
          echo "DEV_ENV set to "$DEV_ENV
          NEW_DEV_ENV="ABC"
          #DEV_ENV=$NEW_DEV_ENV
          echo "DEV_ENV=$NEW_DEV_ENV" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo "DEV_ENV updated to $DEV_ENV"
          cat $GITHUB_ENV
     

          


         


        
