name: Access Environment-Specific Variables

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Choose environment to deploy'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - production

jobs:
  print-env:
    runs-on: ubuntu-latest

    # This ensures GitHub loads the right environment's variables/secrets
    environment:
      name: ${{ github.event.inputs.target_env }}

    steps:
      - name: Echo selected environment
        run: echo "Running in ${{ github.event.inputs.target_env }} environment"

      - name: Read and print environment-specific variables
        run: |
          echo "PROD_ENV = $PROD_ENV"
          echo "DEV_ENV = $DEV_ENV"
        env:
          PROD_ENV: ${{ vars.PROD_ENV }}
          DEV_ENV: ${{ vars.DEV_ENV }}
