name: Print GitHub Environment

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select GitHub environment"
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Production

jobs:
  print-env:
    runs-on: ubuntu-latest

    # GitHub uses this to load environment-specific variables/secrets
    environment:
      name: ${{ github.event.inputs.target_env }}

    steps:
      - name: Print selected GitHub environment
        run: |
          echo "Selected GitHub Environment: $TARGET_ENV"
        env:
          TARGET_ENV: ${{ github.job.environment }}
