name: Print Environment Variable from Dev and Prod

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select environment'
        required: true
        default: development
        type: choice
        options:
          - development
          - production

jobs:
  print-env:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.target_env }}

    steps:
      - name: Echo selected environment
        run: echo "Deploying to ${{ github.event.inputs.target_env }} environment..."

      - name: Set ENV_VALUE
        id: set-env
        run: |
          if [ "${{ github.event.inputs.target_env }}" = "development" ]; then
            echo "ENV_VALUE=${{ vars.DEV_ENV }}" >> $GITHUB_OUTPUT
          else
            echo "ENV_VALUE=${{ vars.PROD_ENV }}" >> $GITHUB_OUTPUT
          fi

      - name: Print
