name: Deploy to Staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print secret (for testing)
        run: echo "API Key is ${{ secrets.API_KEY }}"
