name: Test Vars
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - development
          - Production
jobs:
  test-vars:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Print a GitHub variable
        run: |
          echo "My variable is ${{ vars.MY_VAR }}"
          echo "My development env is ${{ vars.DEV_ENV }}"
          echo "My Dev var is ${{ vars.MY_VAR }}"
          echo "My Prod var is ${{ vars.PROD_VAR }}"


         


        
