name: Print Selected Environment

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select environment'
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Production

jobs:
  print-selected-env:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.target_env }}  # This makes GitHub expose env vars/secrets for that environment

    steps:
      - name: Print selected environment name
        run: echo "Environment selected: ${{ github.event.inputs.target_env }}"
