name: Print Environment Variable from Dev and Prod

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select environment'
        required: true
        default: development
        type: choice
        options:
          - development
          - production

jobs:
  print-env:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.target_env }}

    steps:
      - name: Echo selected environment
        run: echo "Deploying to ${{ github.event.inputs.target_env }} environment..."

      - name: Print environment-specific and common variables
        run: |
          echo "COMMON_ENV = $COMMON_ENV"
          echo "ENV_VALUE = $ENV_VALUE"
        env:
          COMMON_ENV: ${{ vars.COMMON_ENV }}
          ENV_VALUE: ${{ github.event.inputs.target_env == 'development' && vars.DEV_ENV || vars.PROD_ENV }}
