name: Test Vars

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment environment'
        required: true
        default: development
        options:
          - development 
          - Production
jobs:
  test-vars:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Print a GitHub variable
        run: |
          echo "My variable is ${{ vars.MY_VAR }}"
          echo "My variable is ${{ vars.DEV_ENV }}"
         


        
