name: Use Environment-Specific Variables

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Choose environment'
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Production

jobs:
  print-vars:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.target_env }}

    steps:
      - name: Show selected environment
        run: echo "Selected environment: ${{ github.event.inputs.target_env }}"

      - name: Print environment variables
        run: |
          echo "DEV_ENV = $DEV_ENV"
          echo "PROD_ENV = $PROD_ENV"
        env:
          DEV_ENV: ${{ vars.DEV_ENV }}
          PROD_ENV: ${{ vars.PROD_ENV }}

      - name: Debug all environment variables (optional)
        run: env
