name: call shell script

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/deploy.sh

      - name: Run deploy script
        run: ./scripts/deploy.sh
        
        env:
          APP_NAME: my-app
          ENVIRONMENT: development
