name: Env Variable test

on: [push]

env:
  GLOBAL_NAME: Abc 

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      JOB_LEVEL_VAR: "JobValue"  
    steps:
      - name: Use env variables
        run: echo "Hello $GLOBAL_NAME and $JOB_LEVEL_VAR"
