name: TestInput
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment environment'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment"
