name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to?'
        required: true
        default: 'staging'
      version:
        description: 'App version (optional)'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show input values
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version || 'not specified' }}"
