name: Use Variable Group JSON

on:
  workflow_dispatch:

jobs:
  parse-json:
    runs-on: ubuntu-latest
    env:
      CONFIG: ${{ vars.config_VG }}  # Load your variable into the environment

    steps:
      - name: Show raw config
        run: echo "${{ env.CONFIG }}"

      - name: Extract values from JSON
        run: |
          echo "Region: ${{ fromJSON(env.CONFIG).region }}"
          echo "Instance Type: ${{ fromJSON(env.CONFIG).instanceType }}"
