name: Use Variable Group JSON

on:
  workflow_dispatch:

jobs:
  parse-json:
    runs-on: ubuntu-latest

    steps:
      - name: Show raw JSON config
        run: echo "${{ vars.CONFIG_VG }}"  # Direct access to variable

      - name: Extract values from JSON
        run: |
          echo "Region: ${{ fromJSON(vars.CONFIG_VG).region }}"
          echo "Instance Type: ${{ fromJSON(vars.CONFIG_VG).instanceType }}"
