name: Pass Object as Input

on:
  workflow_dispatch:
    inputs:
      objectInput:
        description: 'JSON object input (e.g., {"key1":"value1","key2":"value2"})'
        required: true

jobs:
  process-object:
    runs-on: ubuntu-latest
    steps:
      - name: Print Raw JSON Input
