name: Object Input Workflow
on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration as JSON string'
        required: true
        type: string

jobs:
  use-object:
    runs-on: ubuntu-latest
    steps:
      - name: Print raw config input
        run: echo '${{ inputs.config }}'

      - name: Parse JSON and use values
        run: |
          echo "Parsing input config..."
          CONFIG='${{ inputs.config }}'
          REGION=$(echo "$CONFIG" | jq -r '.region')
          INSTANCE_TYPE=$(echo "$CONFIG" | jq -r '.instanceType')
          echo "Region: $REGION"
          echo "Instance Type: $INSTANCE_TYPE"
