name: Object Input Example

on:
  workflow_dispatch:
    inputs:
      userData:
        description: 'JSON object (e.g. {"name": "John", "age": 30})'
        required: true

jobs:
  use-input:
    runs-on: ubuntu-latest
    steps:
      - name: Parse input JSON
        run: |
          INPUT='${{ inputs.userData }}'

          NAME=$(echo "$INPUT" | jq -r '.name // "unknown"')
          AGE=$(echo "$INPUT" | jq -r '.age // 0')

          echo "Name: $NAME"
          echo "Age: $AGE"
