name: Object Input Workflow

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration as JSON string'
        required: true
        type: string

jobs:
  parse-config:
    runs-on: ubuntu-latest
    steps:
      - name: Print raw input
        run: echo "${{ inputs.config }}"

      - name: Parse config JSON
        shell: bash
        run: |
          echo "Raw input:"
          echo "${{ inputs.config }}"

          # Safely pass the input to a variable
          CONFIG_JSON=$(echo '${{ inputs.config }}' | jq '.')

          echo "Parsed JSON:"
          echo "$CONFIG_JSON"

          REGION=$(echo "$CONFIG_JSON" | jq -r '.region')
          INSTANCE_TYPE=$(echo "$CONFIG_JSON" | jq -r '.instanceType')

          echo "Region: $REGION"
          echo "Instance Type: $INSTANCE_TYPE"
