name: Simple Object Input

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Enter JSON object (e.g. {"name": "Alice", "env": "dev"})'
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Parse input safely
        run: |
          JSON_INPUT="${{ inputs.data }}"

          echo "Raw input: $JSON_INPUT"

          NAME=$(echo "$JSON_INPUT" | jq -r '.name // "default-name"')
          ENV=$(echo "$JSON_INPUT" | jq -r '.env // "default-env"')

          echo "Name: $NAME"
          echo "Environment: $ENV"
