name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/objectInputreusable.yml
    with:
      config: |
        {
          "region": "us-east-1",
          "instanceType": "t2.micro"
        }
