name: Access JSON from env variable

on:
  workflow_dispatch:

env:
  CONFIG: |
    {
      "region": "us-east-1",
      "instanceType": "t2.micro"
    }

jobs:
  access-config:
    runs-on: ubuntu-latest
    steps:
      - name: Show raw config
        run: echo '${{ env.CONFIG }}'

      - name: Access values from CONFIG
        run: |
          echo "Region: ${{ fromJSON(env.CONFIG).region }}"
          echo "Instance Type: ${{ fromJSON(env.CONFIG).instanceType }}"
