name: Simple Object Input

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Enter JSON object (e.g. {"name": "Alice", "env": "dev"})'
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Parse input
        run: |
          JSON='${{ inputs.data }}'

          NAME=$(echo "$JSON" | jq -r '.name // "default-name"')
          ENV=$(echo "$JSON" | jq -r '.env // "default-env"')

          echo "Name: $NAME"
          echo "Environment: $ENV"
