name: Use Variable Group JSON

on:
  workflow_dispatch:

jobs:
  parse-json:
    runs-on: ubuntu-latest
    env:
      CONFIG: ${{ vars.CONFIG_VG }} 
      
    steps:
      - name: Show config
        run: echo "${{ env.CONFIG_VG }}"

      - name: Extract values from JSON
        run: |
          echo "Region: ${{ fromJSON(env.CONFIG_VG).region }}"
          echo "Instance Type: ${{ fromJSON(env.CONFIG_VG).instanceType }}"
