name: Test Vars1
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - development
          - Production

jobs:
  test-vars:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Set initial DEV_ENV and modify it
        run: |
          echo "DEV_ENV=xyz" >> $GITHUB_ENV
          echo "DEV_ENV set to xyz"

      - name: Read modified DEV_ENV, change again, and print
        run: |
          echo "Original DEV_ENV is $DEV_ENV"
          NEW_DEV_ENV="ABC"
          echo "DEV_ENV=$NEW_DEV_ENV" >> $GITHUB_ENV
          echo "DEV_ENV updated to $NEW_DEV_ENV"

      - name: Print final DEV_ENV value
        run: |
          echo "DEV_ENV is now $DEV_ENV"
