name: Simple Vars Example

on:
  workflow_dispatch:

jobs:
  print-vars:
    name: ${{ vars.JOB_NAME }}
    runs-on: ubuntu-latest

    steps:
      - name: Print Config Vars
        run: |
          echo "Project name is: ${{ vars.PROJECT_NAME }}"
          echo "Environment is: ${{ vars.ENVIRONMENT }}"
          echo "Deployed by: ${{ vars.DEPLOYER }}"
